# Unless otherwise stated, the following code was generated by ChatGPT Dec 15, 2022 Version (found 
# at https://chat.openai.com/chat).
# This was in response to the following four prompts from me:
# Prompt 1 (resulting in V1):
#    Write Python script to analyze a folder of .eml files and extract all the fields to a list.
# Prompt 2 (resulting in V2):
#    Please modify the above code so the frequency of each field is recorded too.
# Prompt 3 (resulting in V3):
#    Thank you. Instead of a list, can the extracted fields and their frequency be stored in a 
#    dictionary object with the field as the key and the frequency as the value for that key? 
#    Then convert the dictionary object to prettified json before printing.
# Prompt 4 (supplying comments to the V3 version)
#    Could you now add comments to the code, explaining how it works?
# Prompt 5 (new prompt to ChatGPT Jan 9, 2023 vs)
#   Please write a Python script that can extract and print the body message of an eml file.
# Prompt 6 (supplying comments to the Prompt 5 version)
#   Would you be able to modify that code to turn the body into a JSON object keyed with its field names?

# The code from ChatGPT is as follows:
import os
import email # for parsing .eml files
import json # for prettifying the output
from collections import Counter # for counting the frequency of fields

def extract_fields(eml_file):
    # open the .eml file in binary mode and parse it using the email module
    with open(eml_file, 'rb') as f:
        msg = email.message_from_binary_file(f)
        # create an empty list to store the fields
        fields = []
        # iterate through the fields of the message
        for field in msg.keys():
            # append each field to the list
            fields.append(field)
        # return the list of fields
        return fields

# V1 from ChatGPT---------------------------------#
# def analyze_folder(folder):
#     fields_list = []
#     for eml_file in os.listdir(folder):
#         if eml_file.endswith('.eml'):
#             fields = extract_fields(os.path.join(folder, eml_file))
#             fields_list.extend(fields)
#     return fields_list
#-------- End V1 ---------------------------------#

# V2 from ChatGPT---------------------------------#
# def analyze_folder(folder):
#     fields_list = []
#     for eml_file in os.listdir(folder):
#         if eml_file.endswith('.eml'):
#             fields = extract_fields(os.path.join(folder, eml_file))
#             fields_list.extend(fields)
#     return Counter(fields_list)
#-------- End V2 ---------------------------------#

# V3 from ChatGPT---------------------------------#
def analyze_folder(folder):
    # create an empty list to store the fields
    fields_list = []
    # iterate through the files in the specified folder
    for eml_file in os.listdir(folder):
        # if the file is a .eml file
        if eml_file.endswith('.eml'):
            # extract the fields from the .eml file
            fields = extract_fields(os.path.join(folder, eml_file))
            # add the fields to the list
            fields_list.extend(fields)
    # count the frequency of each field in the list using the Counter class
    fields_counter = Counter(fields_list)
    # create an empty dictionary to store the fields and their frequencies
    fields_dict = {}
    # iterate through the fields and their frequencies
    for field, count in fields_counter.items():
        # add each field and its frequency to the dictionary
        fields_dict[field] = count
    # return the dictionary
    return fields_dict
#-------- End V3 ---------------------------------#

# # Start result of Prompt 5 to ChatGPT, Jan 9, 2023 Vs ---------------------------------#
# def extract_body(file_path):
#     with open(file_path, 'rb') as f:
#         msg = email.message_from_binary_file(f)
#     for part in msg.walk():
#         if part.get_content_type() == "text/plain":
#             body = part.get_payload(decode=True)
#             print(body.decode())
            
# file_path = "path/to/email.eml"
# extract_body(file_path)
# # END result of Prompt 5  ChatGPT -----------------------------------------------------#

# Start result of Prompt 6 to ChatGPT, Jan 9, 2023 Vs ---------------------------------#
def extract_body(file_path):
    with open(file_path, 'rb') as f:
        msg = email.message_from_binary_file(f)
    email_body = {}
    for part in msg.walk():
        if part.get_content_type() == "text/plain":
            body = part.get_payload(decode=True)
            email_body["body"] = body.decode()
    email_body["subject"] = msg["subject"]
    email_body["from"] = msg["from"]
    email_body["to"] = msg["to"]
    print(json.dumps(email_body))
            
file_path = "path/to/email.eml"
extract_body(file_path)
# END result of Prompt 6  ChatGPT -----------------------------------------------------#

# specify the path to the folder
folder = '/path/to/folder'

# fields_list = analyze_folder(folder) # V1 and V2
# print(fields_list) # V1 and V2

# analyze the folder and store the result in a dictionary
fields_dict = analyze_folder(folder) # V3
# convert the dictionary to prettified JSON and print the result
print(json.dumps(fields_dict, indent=4)) # V3
